/**
 * Schema application.
 *
 * Migrations generated by `pnpm db:generate` live in ./drizzle and are applied
 * automatically the first time the database is opened. On top of them we create
 * the FTS5 virtual tables and their sync triggers, which drizzle-kit cannot
 * express — these give us keyword search to blend with vector similarity.
 */
import fs from 'node:fs';
import path from 'node:path';
import type Database from 'better-sqlite3';

/** Directory holding drizzle-kit's generated migrations. */
function migrationsDir(): string {
  return path.resolve(process.cwd(), 'drizzle');
}

/**
 * Applies every `.sql` migration that hasn't run yet.
 *
 * We deliberately do not use `drizzle-orm/better-sqlite3/migrator`: it resolves
 * its journal relative to the bundler's cwd, which is fragile inside a Next
 * server build. Reading the folder ourselves is a dozen lines and never
 * surprises us in production.
 */
export function applySchema(sqlite: Database.Database): void {
  sqlite.exec(`
    CREATE TABLE IF NOT EXISTS __forge_migrations (
      name TEXT PRIMARY KEY,
      applied_at INTEGER NOT NULL
    );
  `);

  const dir = migrationsDir();
  if (fs.existsSync(dir)) {
    const applied = new Set(
      sqlite
        .prepare('SELECT name FROM __forge_migrations')
        .all()
        .map((r) => (r as { name: string }).name),
    );

    const files = fs
      .readdirSync(dir)
      .filter((f) => f.endsWith('.sql'))
      .sort();

    const record = sqlite.prepare(
      'INSERT OR IGNORE INTO __forge_migrations (name, applied_at) VALUES (?, ?)',
    );

    for (const file of files) {
      if (applied.has(file)) continue;
      const sqlText = fs.readFileSync(path.join(dir, file), 'utf8');

      // drizzle-kit separates statements with this marker; splitting on it keeps
      // multi-statement migrations (tables + indexes) atomic per file.
      const statements = sqlText
        .split('--> statement-breakpoint')
        .map((s) => s.trim())
        .filter(Boolean);

      const run = sqlite.transaction(() => {
        for (const statement of statements) sqlite.exec(statement);
        record.run(file, Date.now());
      });
      run();
    }
  }

  applyFullTextSearch(sqlite);
}

/**
 * FTS5 indexes over message and memory text.
 *
 * `content=''` would make these contentless (smallest on disk) but then we could
 * not rebuild them; storing the text twice costs a few MB at personal scale and
 * buys us `rebuild` as a recovery path, which is the right trade here.
 */
function applyFullTextSearch(sqlite: Database.Database): void {
  sqlite.exec(`
    CREATE VIRTUAL TABLE IF NOT EXISTS messages_fts USING fts5(
      id UNINDEXED,
      conversation_id UNINDEXED,
      content,
      tokenize = 'porter unicode61'
    );

    CREATE VIRTUAL TABLE IF NOT EXISTS memories_fts USING fts5(
      id UNINDEXED,
      content,
      title,
      tokenize = 'porter unicode61'
    );
  `);

  // Triggers keep the indexes in lockstep with the base tables, so no application
  // code has to remember to reindex after a write.
  sqlite.exec(`
    CREATE TRIGGER IF NOT EXISTS messages_fts_insert AFTER INSERT ON messages BEGIN
      INSERT INTO messages_fts (id, conversation_id, content)
      VALUES (new.id, new.conversation_id, new.content);
    END;

    CREATE TRIGGER IF NOT EXISTS messages_fts_update AFTER UPDATE OF content ON messages BEGIN
      UPDATE messages_fts SET content = new.content WHERE id = new.id;
    END;

    CREATE TRIGGER IF NOT EXISTS messages_fts_delete AFTER DELETE ON messages BEGIN
      DELETE FROM messages_fts WHERE id = old.id;
    END;

    CREATE TRIGGER IF NOT EXISTS memories_fts_insert AFTER INSERT ON memories BEGIN
      INSERT INTO memories_fts (id, content, title)
      VALUES (new.id, new.content, COALESCE(new.title, ''));
    END;

    CREATE TRIGGER IF NOT EXISTS memories_fts_update AFTER UPDATE OF content, title ON memories BEGIN
      UPDATE memories_fts SET content = new.content, title = COALESCE(new.title, '')
      WHERE id = new.id;
    END;

    CREATE TRIGGER IF NOT EXISTS memories_fts_delete AFTER DELETE ON memories BEGIN
      DELETE FROM memories_fts WHERE id = old.id;
    END;
  `);
}
